// SECRET CONFIG - DO NOT SHARE OR COMMIT THIS FILE
const CONFIG = {
    ANTHROPIC_API_KEY: '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'
};
