// SECRET CONFIG - DO NOT SHARE OR COMMIT THIS FILE
const CONFIG = {
    ANTHROPIC_API_KEY: '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'
};
