// SECRET CONFIG - DO NOT SHARE OR COMMIT THIS FILE
const CONFIG = {
    ANTHROPIC_API_KEY: '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'
};
